### ISSUE TITLE
Provide APK

### ISSUE THREAD

**Issue by i2133514** [mikljohansson/blockade#2]
Hi,

I've previously installed this app and it was fantastic.
Unfortunately I am now in a country that does not have access to Google Play.

Are you able to provide a compiled .apk file as part of the GitHub release by any chance?

I would like to build the app myself, but do not have access to a device capable of running Android Studio.

**Comment by mikljohansson** [comment]
Unfortunately I don't have easy access to the APK anymore, nor a build env to build one. If you'd like to submit a PR that uses Travis CI to build and upload the APK I'd the happy to merge it.

Best,
 Mikael

**Comment by i2133514** [comment]
I understand.

I'm not sure it's possible to set up Tracis CI to build this project, as it depends on your `android-core` library.

**Comment by mikljohansson** [comment]
Ok. Perhaps it'd be possible to build a jar from the android-core lib and
depend on that via JCenter, or check the jar of select classes into this
project. Either case it's a bit of work, unfortunately I just don't have
time to set it up myself at this moment

Best,
 Mikael
